apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: homelab
  source:
    chart: home-assistant
    targetRevision: 13.4.2
    repoURL: https://k8s-at-home.com/charts/
    helm:
      releaseName: home-assistant
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homeassistant
