apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homeassistant

resources:
  - resources/namespace.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/ingress-route.yaml
  - resources/pvc.yaml
